# Generated by Django 3.2.16 on 2022-11-07 17:58

import Core.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Должно создержать слова превосходно или роскошно', validators=[Core.validators.AmazingTextValidator('превосходно', 'роскошно')], verbose_name='описание'),
        ),
    ]
