# Generated by Django 3.2.16 on 2022-11-07 12:33

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221030_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Должно создержать слова превосходно или роскошно', validators=[Core.validators.AmazingTextValidator('превосходно', 'роскошно')], verbose_name='Описание'),
        ),
    ]
