# Generated by Django 3.2.16 on 2022-11-08 15:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='upload',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/gallery/%Y/%m', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='preview',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='uploads/preview/%Y/%m', verbose_name='превью'),
        ),
    ]
