# Generated by Django 3.2.16 on 2022-11-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'обращение', 'verbose_name_plural': 'обращения'},
        ),
    ]
