# Generated by Django 3.2.16 on 2022-12-05 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20221114_2022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemScore',
            new_name='ItemRating',
        ),
        migrations.RenameField(
            model_name='itemrating',
            old_name='score',
            new_name='rating',
        ),
    ]
